
[build]
  publish = "."
  command = "echo 'Build completato'"

[[redirects]]
  from = "/storico.html"
  to = "/storico.html"
  status = 200
  force = false

[[redirects]]
  from = "/storico.html/*"
  to = "/storico.html"
  status = 200
  force = false

[[redirects]]
  from = "/utenti.html"
  to = "/utenti.html"
  status = 200
  force = false

[[redirects]]
  from = "/utenti.html/*"  
  to = "/utenti.html"
  status = 200
  force = false

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
